"""empty message

Revision ID: 27bf67223365
Revises: 1a30aaa81d2f
Create Date: 2016-12-12 16:31:39.753800

"""

# revision identifiers, used by Alembic.
revision = '27bf67223365'
down_revision = '1a30aaa81d2f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts', sa.Column('edit_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Posts', 'edit_date')
    ### end Alembic commands ###
