"""Add thoughts model for Thino-like functionality

Revision ID: 9aa327f4b400
Revises: b4dc62d76aed
Create Date: 2025-10-02 15:40:00.000000

"""

# revision identifiers, used by Alembic.
revision = '9aa327f4b400'
down_revision = 'b4dc62d76aed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thoughts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('thought_type', sa.String(length=20), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thoughts_timestamp'), 'thoughts', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thoughts_timestamp'), table_name='thoughts')
    op.drop_table('thoughts')
    ### end Alembic commands ###