"""Add moods table for mood tracking

Revision ID: a1b2c3d4e5f6
Revises: 9aa327f4b400
Create Date: 2025-10-03 15:00:00.000000

"""

# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '9aa327f4b400'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mood_type', sa.String(length=20), nullable=False),
    sa.Column('custom_mood', sa.String(length=50), nullable=True),
    sa.Column('diary', sa.Text(), nullable=True),
    sa.Column('intensity', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moods_date'), 'moods', ['date'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moods_date'), table_name='moods')
    op.drop_table('moods')
    ### end Alembic commands ###