"""empty message

Revision ID: b4dc62d76aed
Revises: 1208df0f7c8b
Create Date: 2016-10-20 13:52:39.781919

"""

# revision identifiers, used by Alembic.
revision = 'b4dc62d76aed'
down_revision = '1208df0f7c8b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Posts', 'body_html')
    ### end Alembic commands ###
